"""
patch_row_uid.py - add a genuinely globally-unique row_uid column to the
already-consolidated starcoder_tier2.parquet, without re-reading the 210
raw Arrow shards.

ROOT CAUSE (confirmed against 10_load_starcoder_tier2.py's actual code,
not guessed): source_id was never generated by that script - it's copied
verbatim from the upstream StarCoder shards' own "id" column
(cols["id"][j].as_py()). That field is only unique WITHIN whatever
grouping StarCoder itself used, not across this project's full 210-shard
local download - confirmed directly: 6,308,736 of 8,529,290 distinct
source_id values (85% of all 14,838,026 rows) appear in exactly two rows
each.

row_uid here is just the row's position in the table (0..N-1) - unique by
construction, entirely independent of whatever the upstream "id" field
says, so it can never collide regardless of how StarCoder's own numbering
works.

Run:  python patch_row_uid.py
Out:  overwrites starcoder_tier2.parquet in place, with row_uid added as
      a new column. Existing columns and row order are untouched.
"""

import pyarrow as pa
import pyarrow.parquet as pq

import config


def main():
    outdir = config.ensure_output_dir()
    path = outdir / "starcoder_tier2.parquet"

    print(f"Reading {path} ...")
    table = pq.read_table(path)
    n = table.num_rows
    print(f"{n:,} rows")

    if "row_uid" in table.column_names:
        print("row_uid already present - nothing to do.")
        return

    uid_col = pa.array(range(n), type=pa.int64())
    patched = table.append_column("row_uid", uid_col)

    print(f"Writing patched table back to {path} ...")
    pq.write_table(patched, path)

    print(f"Done. row_uid added as a new int64 column, 0..{n-1}, unique "
          f"by construction. All {len(table.column_names)} existing "
          f"columns and row order preserved unchanged.")


if __name__ == "__main__":
    main()
